// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modelos.API.Migrations
{
    [DbContext(typeof(ModelosAPIContext))]
    partial class ModelosAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Torneo.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GesTorneoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GesTorneoId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Torneo.Modelos.EstadisticaJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Goles")
                        .HasColumnType("integer");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasAmarillas")
                        .HasColumnType("integer");

                    b.Property<int>("TarjetasRojas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("EstadisticasJugadores");
                });

            modelBuilder.Entity("Torneo.Modelos.GesTorneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GesTorneos");
                });

            modelBuilder.Entity("Torneo.Modelos.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("Goles")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Targetas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Torneo.Modelos.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GesTorneoId")
                        .HasColumnType("integer");

                    b.Property<int>("GolesA")
                        .HasColumnType("integer");

                    b.Property<int>("GolesB")
                        .HasColumnType("integer");

                    b.Property<bool>("Jugado")
                        .HasColumnType("boolean");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("GesTorneoId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Torneo.Modelos.TablaPosicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Diferencia")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("GesTorneoId")
                        .HasColumnType("integer");

                    b.Property<int>("GolesContra")
                        .HasColumnType("integer");

                    b.Property<int>("GolesFavor")
                        .HasColumnType("integer");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("integer");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.Property<int>("TorneoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("GesTorneoId");

                    b.ToTable("TablaPosiciones");
                });

            modelBuilder.Entity("Torneo.Modelos.Equipo", b =>
                {
                    b.HasOne("Torneo.Modelos.GesTorneo", "GesTorneo")
                        .WithMany("Equipos")
                        .HasForeignKey("GesTorneoId");

                    b.Navigation("GesTorneo");
                });

            modelBuilder.Entity("Torneo.Modelos.EstadisticaJugador", b =>
                {
                    b.HasOne("Torneo.Modelos.Jugador", "Jugador")
                        .WithMany("Estadisticas")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.Partido", "Partido")
                        .WithMany("Estadisticas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("Torneo.Modelos.Jugador", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("Torneo.Modelos.Partido", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.GesTorneo", "GesTorneo")
                        .WithMany("Partidos")
                        .HasForeignKey("GesTorneoId");

                    b.Navigation("Equipo");

                    b.Navigation("GesTorneo");
                });

            modelBuilder.Entity("Torneo.Modelos.TablaPosicion", b =>
                {
                    b.HasOne("Torneo.Modelos.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torneo.Modelos.GesTorneo", "GesTorneo")
                        .WithMany()
                        .HasForeignKey("GesTorneoId");

                    b.Navigation("Equipo");

                    b.Navigation("GesTorneo");
                });

            modelBuilder.Entity("Torneo.Modelos.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("Torneo.Modelos.GesTorneo", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Torneo.Modelos.Jugador", b =>
                {
                    b.Navigation("Estadisticas");
                });

            modelBuilder.Entity("Torneo.Modelos.Partido", b =>
                {
                    b.Navigation("Estadisticas");
                });
#pragma warning restore 612, 618
        }
    }
}
